# only has to pass for python 3.11
name: Static code checks

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  run-code-check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: precommit checker
        uses: pre-commit/action@v3.0.1
